fruits = ["apple", "banana", "cherry", "apple", "mango"]
print("Original List:", fruits)
apple_count = fruits.count("apple")
print("Number of 'apple':", apple_count)
length = len(fruits)
print("Length of list:", length)
fruits.reverse()
print("Reversed List:", fruits)
fruits_copy = fruits.copy()
print("Copied List:", fruits_copy)

List1=['a','b','c','d','e']
List2=[1,2,3,4.3,5.9,0.6]
print(max(List1))
print(max(List2))
print(min(List1))
print(min(List2))
List1.pop(5)
List2.pop()
print(List1)
print(List2)
List1.remove('c')
List2.remove(4.3)
print(List1)
print(List2)
print(List1+List2)